export const QUESTIONS_SEED = [
    { id: 1, texto: "Atende as regras." },
    { id: 2, texto: "Socializa com o grupo." },
    { id: 3, texto: "Isola-se do grupo" },
    { id: 4, texto: "Possui tolerância a frustração." },
    { id: 5, texto: "Respeita colega e professores." },
    { id: 6, texto: "Faz relatos fantasiosos." },
    { id: 7, texto: "Concentra-se nas atividades." },
    { id: 8, texto: "Tem iniciativa." },
    { id: 9, texto: "Sonolência durante as atividades em sala de aula." },
    { id: 10, texto: "Alterações intensas de humor." },
    { id: 11, texto: "Indica oscilação repentina de humor." },
    { id: 12, texto: "Irrita-se com facilidade." },
    { id: 13, texto: "Ansiedade." },
    { id: 14, texto: "Escuta quando seus colegas falam." },
    { id: 15, texto: "Escuta e segue orientação dos professores." },
    { id: 16, texto: "Mantem-se em sala de aula." },
    { id: 17, texto: "Desloca-se muito na sala." },
    { id: 18, texto: "Fala demasiadamente." },
    { id: 19, texto: "É pontual." },
    { id: 20, texto: "É assíduo." },
    { id: 21, texto: "Demonstra desejo de trabalhar." },
    { id: 22, texto: "Apropria-se indevidamente daquilo que não é seu." },
    { id: 23, texto: "Indica hábito de banho diário." },
    { id: 24, texto: "Indica habito de escovação e qualidade na escovação." },
    { id: 25, texto: "Indica cuidado com a aparência e limpeza do uniforme." },
    { id: 26, texto: "Indica autonomia quanto a estes hábitos (23, 24, 25)." },
    { id: 27, texto: "Indica falta do uso de medicação com oscilações de comportamento.", },
    { id: 28, texto: "Tem meio articulado de conseguir receitas e aquisições das medicações.", },
    { id: 29, texto: "Traz seus materiais organizados." },
    { id: 30, texto: "Usa transporte coletivo." },
    { id: 31, texto: "Tem iniciativa diante das atividades propostas." },
    { id: 32, texto: "Localiza-se no espaço da Instituição." },
    { id: 33, texto: "Situa-se nas trocas de sala e atividades." },
    { id: 34, texto: "Interage par a par." },
    { id: 35, texto: "Interage em grupo." },
    { id: 36, texto: "Cria conflitos e intrigas." },
    { id: 37, texto: "Promove a harmonia." },
    { id: 38, texto: "Faz intrigas entre colegas x professores." },
    { id: 39, texto: "Demonstra interesse em participar das atividades extraclasses.", },
    { id: 40, texto: "Você percebe que existe interação/participação da família em apoio ao usuário na Instituição.", },
    { id: 41, texto: "Você percebe superproteção por parte da família quanto a autonomia do usuário.", },
    { id: 42, texto: "Usuário traz relatos negativos da família (de forma geral).", },
    { id: 43, texto: "Usuário traz relatos positivos da família (de forma geral).", },
    { id: 44, texto: "Você percebe incentivo quanto a busca de autonomia para o usuário por parte da família.", },
    { id: 45, texto: "Você percebe incentivo quanto a inserção do usuário no mercado de trabalho por parte da família.", },
    { id: 46, texto: "Traz os documentos enviados pela Instituição assinado." }
];